### ISSUE TITLE
是否可以添加自定义读取cs或命令行参数执行？

### ISSUE THREAD

**Issue by NewNeko-2022** [GreenDamTan/swadmin#14]
希望您可以增加一些功能以改进易用性。
您目前版本的程序在实际使用中需要开启所有debug模式，以便对照使用、导出、导入；
希望可以带参数执行，以便批量导出。
比如：
swadmin.exe -Client -Ver JP1.11.19.0 -de tb_achievement.res txt/csv/etc
swadmin.exe -Server -Ver Server_default -en tb_achievement.txt/csv/etc
swadmin.exe -Server -Ver Server_default -enfolder ./Server_res_123
或
swadmin.exe -Server -Verfolder ./Server_default -enfolder ./data12.v.defiles
进行批量解压自定义文件夹中存在的规则。
不过我个人还是更希望是前者，因为我并没有维护[TableStruct]的能力。

如果需要赞助希望不要太高....

**Comment by GreenDamTan** [comment]
您可以明确需求，并进行适当的拆分。

**Comment by GreenDamTan** [comment]
因无具体需求，关闭issues
